version: '3'

services:
  fastapi:
    build: api/segmentation
    ports: 
      - 8000:8000
    networks:
      - deploy_network
    container_name: fastapi-mult

networks:
  deploy_network:
    driver: bridge